### ISSUE TITLE
Nos quedó la embarrá.-

### ISSUE THREAD

**Issue by mthompsonc** [mthompsonc/library-project#16]
Tuvimos un problema con el orden de archivos que estaba interfiriendo con el buen funcionamiento de nuestra librería. Luego creamos una nueva rama, que no resultó como esperábamos y tuvimos que borrarla, para así crearla nuevamente desde la rama Master y logramos subir todos los archivos nuevamente. 👍

**Comment by hobilin** [comment]
Logramos ordenar todo correctamente y ahora los tests funcionan bien con jsdom, solo faltaría agregar un test que aplique funcionalidad y también pasar las funciones a plugin, pero creo que eso se puede hacer simple con el $.fn, tenemos que investigar más eso.
