### ISSUE TITLE
Cambiamos una función de nuestro proyecto.

### ISSUE THREAD

**Issue by mthompsonc** [mthompsonc/library-project#26]
La cambiamos, porque no funcionaba bien con respecto al scroll y la reemplazamos con un botón para subir al top de la página y quedó funcionando a la perfección.

**Comment by hobilin** [comment]
el nuevo plugin funciona al ser aplicado a cualquier div vacío ya que desde la función misma se le agrega el botón junto con la animación de subir al top de la página y desaparecer al hacerlo.

**Comment by mthompsonc** [comment]
Cabe mencionar, que no importa el orden donde se ponga el div vacío donde se aplicará la función, ya que el botón para subir al top de la página aparecerá de todas formas.
