### ISSUE TITLE
agregar tests

### ISSUE THREAD

**Issue by hobilin** [mthompsonc/library-project#5]
Agregar tests que describan la API de tu librería y los casos de uso esperados.

**Comment by hobilin** [comment]
Falta idear más tests y ver el tema de que no agarra el Jquery ni los elementos del html

**Comment by mthompsonc** [comment]
[https://gph.is/1cO1G6K](url)

**Comment by hobilin** [comment]
tests funcionando a la perfección, tenemos que ver si crear más o dejar los que están. por lo que aún no cerraré este issue.

**Comment by mthompsonc** [comment]
Cerraré este issue, esperando feedback y si es necesario, lo crearé en el millestone Semana 3.
