### ISSUE TITLE
Crear funciones básicas

### ISSUE THREAD

**Issue by hobilin** [mthompsonc/library-project#6]
- Función div que se mueve de izquierda a centro.

- Función div que se mueve de derecha a centro.

- Función div que se despliega.

- Funciónes se activan al div aperecer en pantalla.

**Comment by hobilin** [comment]
funciones para que los divs se muevan de la derecha e izquierda al centro y la función para que se despliegue casi listas. El hecho de que se active la función solo cuando el div se muestre en pantalla está listo, solo falta pasarlas a plugin, y arreglar un detalle con la altura a la que se activa la función

**Comment by mthompsonc** [comment]
Problemas al pasarlo a plugings, ya que no toman las funciones.

**Comment by mthompsonc** [comment]
Funciones básicas creadas, listas funcionando.
