### ISSUE TITLE
Primer codereview

### ISSUE THREAD

**Issue by MarciaMillanao** [mthompsonc/library-project#9]
**Readme:** Esta Bien .No olviden agregar las nuevas dependencias de testeo. Pueden utilizar como referencia los siguientes repositorios: https://github.com/needim/noty/blob/master/README.markdown https://github.com/GetmeUK/ContentTools/blob/master/README.md

**Issues:** Falta interacción entre ustedes, no solo crearlos.

Lo demás esta ok, sigan trabajando así.

--
_Alexandra, Fabián y Marcia_

**Comment by mthompsonc** [comment]
Hemos logrado interactuar más en los Issues y además hemos actualizado el repositorio. 
Gracias por el feedback.-
